Repository Sa-Yee/BucketBingo-Client, pull requests merged in 2021-11, with the labels that each got.

#39 [Client] #38 feat:add map API
  .env.example
  .gitignore
  package.json
  public/index.html
  src/components/aboutus/Introduce.tsx
  src/components/aboutus/Map.tsx
  src/components/aboutus/_aboutus.scss
  src/components/bingo/Bingo.tsx
  src/components/bingo/_bingo.scss
  src/components/common/sidebar/Sidebar.tsx
  src/components/makebingo/BingoMaker.tsx
  src/components/makebingo/_bingoMaker.scss
  src/components/mypage/MybingoInMypage.tsx
  src/components/ranking/RankingList.tsx
  src/components/watchbingo/BingoPost.tsx
  src/components/watchbingo/_bingoPost.scss
  src/images/profile/soyou.png
  src/images/profile/yoon.jpg
  src/index.tsx
  src/pages/AboutUs.tsx
  src/redux/actions/types.tsx
  src/redux/actions/userAction.tsx
  src/redux/reducers/bingoReducer.js
  src/redux/reducers/communityReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/mypageReducer.js
  src/redux/reducers/userReducer.js
  src/redux/store/store.js
  src/scss/main.scss
  src/style.css
  yarn.lock
Labels: client, C:2h, high

#42 [Client] #40 feat:add dropbox
  src/components/aboutus/Map.tsx
  src/components/aboutus/_aboutus.scss
  src/components/home/_home.scss
  src/components/mypage/MybingoInMypage.tsx
  src/components/mypage/_mybingoInMypage.scss
  src/components/ranking/RankingList.tsx
  src/components/ranking/_rankingList.scss
  src/components/watchbingo/BingoPost.tsx
  src/components/watchbingo/_bingoPost.scss
  src/style.css
Labels: client, C:3h, high

#44 [Client] #22 modify:fontweight
  src/components/landing/_landing.scss
  src/style.css
Labels: client, C:0.5h, row

#46 add slide in mypage bingo
  src/components/mypage/MybingoInMypage.tsx
  src/components/mypage/_mybingoInMypage.scss
  src/style.css
Labels: client, C:2h, high

#60 feat : redux saga setting
  src/api/bingo.js
  src/api/ranking.js
  src/api/user.js
  src/modules/bingo.js
  src/modules/index.js
  src/modules/ranking.js
  src/modules/user.js
Labels: client, C:1h, high

#62 feat : oauth login
  src/components/common/login/Login.tsx
  src/modules/bingo.js
  src/modules/user.js
Labels: client, C:1h, high

#63 modify: add react_app env name
  .env.example
  src/components/common/login/Login.tsx
Labels: bug

#68 redux
  package.json
  src/App.tsx
  src/api/bingo.js
  src/api/ranking.js
  src/api/user.js
  src/app/store.tsx
  src/components/common/login/Login.tsx
  src/components/home/FirstHome.tsx
  src/features/user/action.ts
  src/features/user/user.tsx
  src/index.tsx
  src/modules/bingo.js
  src/modules/index.js
  src/modules/ranking.js
  src/modules/user.js
  tsconfig.json
  yarn.lock
Labels: client, C:3h, high
